name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: Swatinem/rust-cache@v1.3.0
      with:
        working-directory: backend
    - uses: Swatinem/rust-cache@v1.3.0
      with:
        working-directory: frontends

    - uses: actions/checkout@v2
    - name: Test backend
      run: cd backend && cargo test
    - name: Test frontends
      run: cd frontends && cargo test
